name: CD

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: docker permission 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.FIC_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: | 
          whoami
          sudo chmod 666 /var/run/docker.sock
          sudo chown -R fic:fic /home/fic/app/
    - name: github
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - run: npm install
    - run: npm run build
   
    - name: Deploy to dev
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.FIC_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: | 
          whoami
          sudo chmod 777 server_deploy.sh
          sudo ./server_deploy.sh
          sudo chown -R fic:fic /home/fic/app/
